import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Shared/Footer";
import Navbar from "@/components/Shared/Navbar";
import ScrollToTopButton from "@/components/Shared/ScrollToTopButton";
import { FilteredCoursesProvider } from "@/contexts/FilteredCoursesContext";
import Toast from './nextToast'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Global Education Care",
  description: "Generated by AN Tech Innovation",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <FilteredCoursesProvider>
        <body className={inter.className}>
          <Toast />
          <Navbar></Navbar>
          {children}
          <ScrollToTopButton></ScrollToTopButton>
          <Footer></Footer>

        </body>

      </FilteredCoursesProvider>
    </html>
  );
}
