export const courses = [
  {
    subject: "Anthropology",
    level: "postgraduate",
    destination: "Ireland",
    university: "National University of Ireland, Galway",
    ieltsScore: 6.5,
    location: "Galway",
    campusCity: "Galway",
    tuitionFees: "€17,750 per year",
    applicationFees: "€35",
    duration: "3 years",
    intake: "September",
    worldRank: "259",
    internationalStudent: "17%",
    courseDetailLink: "https://www.nuigalway.ie/courses/undergraduate-courses/anthropology.html",
    universityDetailLink: "https://www.nuigalway.ie/"
  },
  {
    subject: "Law",
    level: "undergraduate",
    destination: "USA",
    university: "Harvard University",
    ieltsScore: 6.5,
    location: "Massachusetts",
    campusCity: "Cambridge",
    tuitionFees: "$51,143 per year",
    applicationFees: "$75",
    duration: "4 years",
    intake: "Fall",
    worldRank: "1",
    internationalStudent: "14%",
    courseDetailLink: "https://college.harvard.edu/academics",
    universityDetailLink: "https://www.harvard.edu/"
  },
  {
    subject: "Computer Science",
    level: "phD",
    destination: "USA",
    university: "Stanford University",
    ieltsScore: 7.0,
    location: "California",
    campusCity: "Stanford",
    tuitionFees: "$56,169 per year",
    applicationFees: "$90",
    duration: "4 years",
    intake: "Fall",
    worldRank: "2",
    internationalStudent: "22%",
    courseDetailLink: "https://cs.stanford.edu/degrees/ug/",
    universityDetailLink: "https://www.stanford.edu/"
  },
  {
    subject: "Business Administration",
    level: "phD",
    destination: "USA",
    university: "University of Pennsylvania",
    ieltsScore: 7.5,
    location: "Pennsylvania",
    campusCity: "Philadelphia",
    tuitionFees: "$60,042 per year",
    applicationFees: "$75",
    duration: "4 years",
    intake: "Fall",
    worldRank: "6",
    internationalStudent: "19%",
    courseDetailLink: "https://undergrad.wharton.upenn.edu/",
    universityDetailLink: "https://www.upenn.edu/"
  },
  {
    subject: "Mechanical Engineering",
    level: "postgraduate",
    destination: "Canada",
    university: "University of Toronto",
    ieltsScore: 6.5,
    location: "Ontario",
    campusCity: "Toronto",
    tuitionFees: "CAD $58,160 per year",
    applicationFees: "CAD $180",
    duration: "4 years",
    intake: "Fall",
    worldRank: "18",
    internationalStudent: "25%",
    courseDetailLink: "https://undergrad.engineering.utoronto.ca/",
    universityDetailLink: "https://www.utoronto.ca/"
  },
  {
    subject: "Medicine",
    level: "postgraduate",
    destination: "UK",
    university: "University of Oxford",
    ieltsScore: 7.5,
    location: "England",
    campusCity: "Oxford",
    tuitionFees: "£36,800 per year",
    applicationFees: "£75",
    duration: "6 years",
    intake: "October",
    worldRank: "5",
    internationalStudent: "21%",
    courseDetailLink: "https://www.medsci.ox.ac.uk/study/medicine",
    universityDetailLink: "https://www.ox.ac.uk/"
  },
  {
    subject: "Economics",
    level: "undergraduate",
    destination: "UK",
    university: "London School of Economics",
    ieltsScore: 7.0,
    location: "England",
    campusCity: "London",
    tuitionFees: "£21,570 per year",
    applicationFees: "£80",
    duration: "3 years",
    intake: "September",
    worldRank: "4",
    internationalStudent: "70%",
    courseDetailLink: "https://www.lse.ac.uk/study-at-lse/Undergraduate/Degree-programmes-2023/BSc-Economics",
    universityDetailLink: "https://www.lse.ac.uk/"
  },
  {
    subject: "Software Engineering",
    level: "undergraduate",
    destination: "Australia",
    university: "University of Melbourne",
    ieltsScore: 6.5,
    location: "Victoria",
    campusCity: "Melbourne",
    tuitionFees: "AUD $41,912 per year",
    applicationFees: "AUD $100",
    duration: "4 years",
    intake: "February",
    worldRank: "31",
    internationalStudent: "42%",
    courseDetailLink: "https://study.unimelb.edu.au/find/courses/undergraduate/bachelor-of-software-engineering/",
    universityDetailLink: "https://www.unimelb.edu.au/"
  },
  {
    subject: "Architecture",
    level: "undergraduate",
    destination: "Canada",
    university: "McGill University",
    ieltsScore: 6.5,
    location: "Quebec",
    campusCity: "Montreal",
    tuitionFees: "CAD $18,110 per year",
    applicationFees: "CAD $114",
    duration: "3.5 years",
    intake: "Fall",
    worldRank: "27",
    internationalStudent: "30%",
    courseDetailLink: "https://www.mcgill.ca/architecture/programs/undergraduate",
    universityDetailLink: "https://www.mcgill.ca/"
  },
  {
    subject: "Psychology",
    level: "postgraduate",
    destination: "New Zealand",
    university: "University of Auckland",
    ieltsScore: 6.5,
    location: "Auckland",
    campusCity: "Auckland",
    tuitionFees: "NZD $33,688 per year",
    applicationFees: "NZD $100",
    duration: "3 years",
    intake: "March",
    worldRank: "81",
    internationalStudent: "20%",
    courseDetailLink: "https://www.auckland.ac.nz/en/study/study-options/find-a-study-option/psychology.html",
    universityDetailLink: "https://www.auckland.ac.nz/"
  },
  {
    subject: "Pharmacy",
    level: "undergraduate",
    destination: "Ireland",
    university: "Trinity College Dublin",
    ieltsScore: 6.0,
    location: "Dublin",
    campusCity: "Dublin",
    tuitionFees: "€25,000 per year",
    applicationFees: "€55",
    duration: "5 years",
    intake: "September",
    worldRank: "101",
    internationalStudent: "30%",
    courseDetailLink: "https://www.tcd.ie/courses/undergraduate/az/course.php?id=DUBSC-PHA",
    universityDetailLink: "https://www.tcd.ie/"
  },
  {
    subject: "Electrical Engineering",
    level: "undergraduate",
    destination: "USA",
    university: "MIT",
    ieltsScore: 7.0,
    location: "Massachusetts",
    campusCity: "Cambridge",
    tuitionFees: "$53,790 per year",
    applicationFees: "$75",
    duration: "4 years",
    intake: "Fall",
    worldRank: "1",
    internationalStudent: "10%",
    courseDetailLink: "https://www.eecs.mit.edu/undergraduate-programs/",
    universityDetailLink: "https://www.mit.edu/"
  },
  {
    subject: "Chemical Engineering",
    level: "postgraduate",
    destination: "USA",
    university: "Caltech",
    ieltsScore: 5.5,
    location: "California",
    campusCity: "Pasadena",
    tuitionFees: "$54,570 per year",
    applicationFees: "$75",
    duration: "4 years",
    intake: "Fall",
    worldRank: "5",
    internationalStudent: "8%",
    courseDetailLink: "https://www.che.caltech.edu/",
    universityDetailLink: "https://www.caltech.edu/"
  },
  {
    subject: "Physics",
    level: "undergraduate",
    destination: "USA",
    university: "Princeton University",
    ieltsScore: 7.0,
    location: "New Jersey",
    campusCity: "Princeton",
    tuitionFees: "$53,890 per year",
    applicationFees: "$70",
    duration: "4 years",
    intake: "Fall",
    worldRank: "9",
    internationalStudent: "12%",
    courseDetailLink: "https://www.princeton.edu/academics/area-of-study/physics",
    universityDetailLink: "https://www.princeton.edu/"
  },
  {
    "subject": "Anthropology",
    "level": "undergraduate",
    "destination": "Ireland",
    "university": "National University of Ireland, Galway",
    "ieltsScore": 6.0,
    "location": "Galway",
    "campusCity": "Galway",
    "tuitionFees": "€17,750 per year",
    "applicationFees": "€35",
    "duration": "3 years",
    "intake": "September",
    "worldRank": 259,
    "internationalStudent": "17%",
    "courseDetailLink": "https://www.nuigalway.ie/courses/undergraduate-courses/anthropology.html",
    "universityDetailLink": "https://www.nuigalway.ie/"
  },
  {
    "subject": "Biology",
    "level": "postgraduate",
    "destination": "Australia",
    "university": "University of Melbourne",
    "ieltsScore": 6.5,
    "location": "Melbourne",
    "campusCity": "Melbourne",
    "tuitionFees": "A$40,000 per year",
    "applicationFees": "A$100",
    "duration": "3 years",
    "intake": "February",
    "worldRank": 32,
    "internationalStudent": "25%",
    "courseDetailLink": "https://study.unimelb.edu.au/find/courses/undergraduate/bachelor-of-science/majors/biology/",
    "universityDetailLink": "https://www.unimelb.edu.au/"
  },
  {
    "subject": "Computer Science",
    "level": "undergraduate",
    "destination": "USA",
    "university": "Stanford University",
    "ieltsScore": 7.0,
    "location": "Stanford",
    "campusCity": "Stanford",
    "tuitionFees": "$53,529 per year",
    "applicationFees": "$90",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 2,
    "internationalStudent": "23%",
    "courseDetailLink": "https://cs.stanford.edu/Undergrad/",
    "universityDetailLink": "https://www.stanford.edu/"
  },
  {
    "subject": "Economics",
    "level": "postgraduate",
    "destination": "UK",
    "university": "University of Oxford",
    "ieltsScore": 7.5,
    "location": "Oxford",
    "campusCity": "Oxford",
    "tuitionFees": "£24,750 per year",
    "applicationFees": "£75",
    "duration": "3 years",
    "intake": "October",
    "worldRank": 1,
    "internationalStudent": "20%",
    "courseDetailLink": "https://www.ox.ac.uk/admissions/undergraduate/courses-listing/economics-and-management",
    "universityDetailLink": "https://www.ox.ac.uk/"
  },
  {
    "subject": "Engineering",
    "level": "postgraduate",
    "destination": "Canada",
    "university": "University of Toronto",
    "ieltsScore": 6.5,
    "location": "Toronto",
    "campusCity": "Toronto",
    "tuitionFees": "C$58,160 per year",
    "applicationFees": "C$180",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 18,
    "internationalStudent": "23%",
    "courseDetailLink": "https://engineering.utoronto.ca/",
    "universityDetailLink": "https://www.utoronto.ca/"
  },
  {
    "subject": "Environmental Science",
    "level": "undergraduate",
    "destination": "Ireland",
    "university": "Trinity College Dublin",
    "ieltsScore": 6.5,
    "location": "Dublin",
    "campusCity": "Dublin",
    "tuitionFees": "€21,000 per year",
    "applicationFees": "€55",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 98,
    "internationalStudent": "24%",
    "courseDetailLink": "https://www.tcd.ie/courses/undergraduate/env-sci/",
    "universityDetailLink": "https://www.tcd.ie/"
  },
  {
    "subject": "Geography",
    "level": "undergraduate",
    "destination": "UK",
    "university": "University of Cambridge",
    "ieltsScore": 7.5,
    "location": "Cambridge",
    "campusCity": "Cambridge",
    "tuitionFees": "£22,227 per year",
    "applicationFees": "£60",
    "duration": "3 years",
    "intake": "October",
    "worldRank": 3,
    "internationalStudent": "18%",
    "courseDetailLink": "https://www.geog.cam.ac.uk/undergraduate/",
    "universityDetailLink": "https://www.cam.ac.uk/"
  },
  {
    "subject": "History",
    "level": "undergraduate",
    "destination": "Canada",
    "university": "University of British Columbia",
    "ieltsScore": 6.0,
    "location": "Vancouver",
    "campusCity": "Vancouver",
    "tuitionFees": "C$54,541 per year",
    "applicationFees": "C$125",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 34,
    "internationalStudent": "28%",
    "courseDetailLink": "https://history.ubc.ca/",
    "universityDetailLink": "https://www.ubc.ca/"
  },
  {
    "subject": "Law",
    "level": "phD",
    "destination": "Australia",
    "university": "University of Sydney",
    "ieltsScore": 7.0,
    "location": "Sydney",
    "campusCity": "Sydney",
    "tuitionFees": "A$46,000 per year",
    "applicationFees": "A$150",
    "duration": "5 years",
    "intake": "March",
    "worldRank": 40,
    "internationalStudent": "29%",
    "courseDetailLink": "https://www.sydney.edu.au/courses/courses/uc/bachelor-of-laws.html",
    "universityDetailLink": "https://www.sydney.edu.au/"
  },
  {
    "subject": "Mathematics",
    "level": "postgraduate",
    "destination": "USA",
    "university": "Massachusetts Institute of Technology",
    "ieltsScore": 7.5,
    "location": "Cambridge",
    "campusCity": "Cambridge",
    "tuitionFees": "$53,790 per year",
    "applicationFees": "$75",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 1,
    "internationalStudent": "33%",
    "courseDetailLink": "https://math.mit.edu/undergraduate/",
    "universityDetailLink": "https://www.mit.edu/"
  },
  {
    "subject": "Medicine",
    "level": "undergraduate",
    "destination": "UK",
    "university": "Imperial College London",
    "ieltsScore": 7.0,
    "location": "London",
    "campusCity": "London",
    "tuitionFees": "£42,000 per year",
    "applicationFees": "£75",
    "duration": "6 years",
    "intake": "October",
    "worldRank": 7,
    "internationalStudent": "18%",
    "courseDetailLink": "https://www.imperial.ac.uk/study/ug/courses/school-of-medicine/medicine/",
    "universityDetailLink": "https://www.imperial.ac.uk/"
  },
  {
    "subject": "Nursing",
    "level": "phD",
    "destination": "Canada",
    "university": "McGill University",
    "ieltsScore": 6.0,
    "location": "Montreal",
    "campusCity": "Montreal",
    "tuitionFees": "C$52,304 per year",
    "applicationFees": "C$114",
    "duration": "3 years",
    "intake": "September",
    "worldRank": 31,
    "internationalStudent": "30%",
    "courseDetailLink": "https://www.mcgill.ca/nursing/",
    "universityDetailLink": "https://www.mcgill.ca/"
  },
  {
    "subject": "Philosophy",
    "level": "undergraduate",
    "destination": "Ireland",
    "university": "University College Dublin",
    "ieltsScore": 6.5,
    "location": "Dublin",
    "campusCity": "Dublin",
    "tuitionFees": "€19,900 per year",
    "applicationFees": "€50",
    "duration": "3 years",
    "intake": "September",
    "worldRank": 177,
    "internationalStudent": "26%",
    "courseDetailLink": "https://www.ucd.ie/courses/undergrad/philosophy/",
    "universityDetailLink": "https://www.ucd.ie/"
  },
  {
    "subject": "Physics",
    "level": "undergraduate",
    "destination": "Australia",
    "university": "Australian National University",
    "ieltsScore": 5.5,
    "location": "Canberra",
    "campusCity": "Canberra",
    "tuitionFees": "A$43,000 per year",
    "applicationFees": "A$100",
    "duration": "3 years",
    "intake": "February",
    "worldRank": 29,
    "internationalStudent": "36%",
    "courseDetailLink": "https://science.anu.edu.au/study/bachelor-degrees/bachelor-physics",
    "universityDetailLink": "https://www.anu.edu.au/"
  },
  {
    "subject": "Political Science",
    "level": "postgraduate",
    "destination": "UK",
    "university": "London School of Economics",
    "ieltsScore": 7.0,
    "location": "London",
    "campusCity": "London",
    "tuitionFees": "£22,430 per year",
    "applicationFees": "£80",
    "duration": "3 years",
    "intake": "September",
    "worldRank": 6,
    "internationalStudent": "27%",
    "courseDetailLink": "https://www.lse.ac.uk/study-at-lse/Undergraduate/Degree-programmes-2021/BSc-Politics-and-International-Relations",
    "universityDetailLink": "https://www.lse.ac.uk/"
  },
  {
    "subject": "Psychology",
    "level": "undergraduate",
    "destination": "USA",
    "university": "Harvard University",
    "ieltsScore": 6.0,
    "location": "Cambridge",
    "campusCity": "Cambridge",
    "tuitionFees": "$51,904 per year",
    "applicationFees": "$75",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 3,
    "internationalStudent": "25%",
    "courseDetailLink": "https://psychology.fas.harvard.edu/",
    "universityDetailLink": "https://www.harvard.edu/"
  },
  {
    "subject": "Sociology",
    "level": "undergraduate",
    "destination": "Canada",
    "university": "University of Alberta",
    "ieltsScore": 6.5,
    "location": "Edmonton",
    "campusCity": "Edmonton",
    "tuitionFees": "C$33,980 per year",
    "applicationFees": "C$125",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 119,
    "internationalStudent": "16%",
    "courseDetailLink": "https://www.ualberta.ca/sociology/",
    "universityDetailLink": "https://www.ualberta.ca/"
  },
  {
    "subject": "Statistics",
    "level": "undergraduate",
    "destination": "UK",
    "university": "University of Edinburgh",
    "ieltsScore": 5.5,
    "location": "Edinburgh",
    "campusCity": "Edinburgh",
    "tuitionFees": "£22,000 per year",
    "applicationFees": "£60",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 20,
    "internationalStudent": "38%",
    "courseDetailLink": "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=G300",
    "universityDetailLink": "https://www.ed.ac.uk/"
  },
  {
    "subject": "Theatre Studies",
    "level": "undergraduate",
    "destination": "USA",
    "university": "Yale University",
    "ieltsScore": 6.0,
    "location": "New Haven",
    "campusCity": "New Haven",
    "tuitionFees": "$55,500 per year",
    "applicationFees": "$80",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 14,
    "internationalStudent": "21%",
    "courseDetailLink": "https://theaterstudies.yale.edu/",
    "universityDetailLink": "https://www.yale.edu/"
  },
  {
    "subject": "Veterinary Science",
    "level": "postgraduate",
    "destination": "Australia",
    "university": "University of Queensland",
    "ieltsScore": 7.0,
    "location": "Brisbane",
    "campusCity": "Brisbane",
    "tuitionFees": "A$48,800 per year",
    "applicationFees": "A$100",
    "duration": "5 years",
    "intake": "February",
    "worldRank": 47,
    "internationalStudent": "21%",
    "courseDetailLink": "https://future-students.uq.edu.au/study/program/Bachelor-of-Veterinary-Science-Honours-2396",
    "universityDetailLink": "https://www.uq.edu.au/"
  },
  {
    "subject": "Anthropology",
    "level": "phD",
    "destination": "Canada",
    "university": "University of Calgary",
    "ieltsScore": 6.0,
    "location": "Calgary",
    "campusCity": "Calgary",
    "tuitionFees": "C$28,599 per year",
    "applicationFees": "C$145",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 242,
    "internationalStudent": "16%",
    "courseDetailLink": "https://arts.ucalgary.ca/anthropology-archaeology/future-students/undergraduate",
    "universityDetailLink": "https://www.ucalgary.ca/"
  },
  {
    "subject": "Art History",
    "level": "phD",
    "destination": "USA",
    "university": "University of California, Berkeley",
    "ieltsScore": 6.5,
    "location": "Berkeley",
    "campusCity": "Berkeley",
    "tuitionFees": "$44,008 per year",
    "applicationFees": "$70",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 5,
    "internationalStudent": "23%",
    "courseDetailLink": "http://arthistory.berkeley.edu/",
    "universityDetailLink": "https://www.berkeley.edu/"
  },
  {
    "subject": "Biochemistry",
    "level": "phD",
    "destination": "UK",
    "university": "University of Bristol",
    "ieltsScore": 7.5,
    "location": "Bristol",
    "campusCity": "Bristol",
    "tuitionFees": "£24,000 per year",
    "applicationFees": "£60",
    "duration": "3 years",
    "intake": "September",
    "worldRank": 58,
    "internationalStudent": "23%",
    "courseDetailLink": "https://www.bristol.ac.uk/study/undergraduate/2022/biochemistry/",
    "universityDetailLink": "https://www.bristol.ac.uk/"
  },
  {
    "subject": "Chemistry",
    "level": "undergraduate",
    "destination": "Ireland",
    "university": "University of Limerick",
    "ieltsScore": 6.5,
    "location": "Limerick",
    "campusCity": "Limerick",
    "tuitionFees": "€16,500 per year",
    "applicationFees": "€35",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 501,
    "internationalStudent": "15%",
    "courseDetailLink": "https://www.ul.ie/courses/bachelor-science-chemistry",
    "universityDetailLink": "https://www.ul.ie/"
  },
  {
    "subject": "Civil Engineering",
    "level": "undergraduate",
    "destination": "Australia",
    "university": "Monash University",
    "ieltsScore": 7.5,
    "location": "Melbourne",
    "campusCity": "Melbourne",
    "tuitionFees": "A$43,000 per year",
    "applicationFees": "A$100",
    "duration": "4 years",
    "intake": "February",
    "worldRank": 58,
    "internationalStudent": "30%",
    "courseDetailLink": "https://www.monash.edu/study/courses/find-a-course/2021/civil-engineering-e3001",
    "universityDetailLink": "https://www.monash.edu/"
  },
  {
    "subject": "Classical Studies",
    "level": "undergraduate",
    "destination": "UK",
    "university": "Durham University",
    "ieltsScore": 6.5,
    "location": "Durham",
    "campusCity": "Durham",
    "tuitionFees": "£21,730 per year",
    "applicationFees": "£75",
    "duration": "3 years",
    "intake": "October",
    "worldRank": 86,
    "internationalStudent": "22%",
    "courseDetailLink": "https://www.durham.ac.uk/study/courses/ba-classics-q800/",
    "universityDetailLink": "https://www.durham.ac.uk/"
  },
  {
    "subject": "Creative Writing",
    "level": "postgraduate",
    "destination": "USA",
    "university": "New York University",
    "ieltsScore": 8.0,
    "location": "New York",
    "campusCity": "New York",
    "tuitionFees": "$54,880 per year",
    "applicationFees": "$80",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 42,
    "internationalStudent": "22%",
    "courseDetailLink": "https://tisch.nyu.edu/content/nyu-as-site/tisch/home/programs/degrees/ba-creative-writing.html",
    "universityDetailLink": "https://www.nyu.edu/"
  },
  {
    "subject": "Criminology",
    "level": "postgraduate",
    "destination": "Canada",
    "university": "University of Ottawa",
    "ieltsScore": 7.5,
    "location": "Ottawa",
    "campusCity": "Ottawa",
    "tuitionFees": "C$37,000 per year",
    "applicationFees": "C$156",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 145,
    "internationalStudent": "18%",
    "courseDetailLink": "https://socialsciences.uottawa.ca/criminology/",
    "universityDetailLink": "https://www.uottawa.ca/"
  },
  {
    "subject": "Data Science",
    "level": "postgraduate",
    "destination": "Australia",
    "university": "University of New South Wales",
    "ieltsScore": 6.5,
    "location": "Sydney",
    "campusCity": "Sydney",
    "tuitionFees": "A$45,600 per year",
    "applicationFees": "A$125",
    "duration": "4 years",
    "intake": "February",
    "worldRank": 44,
    "internationalStudent": "32%",
    "courseDetailLink": "https://www.unsw.edu.au/study/undergraduate/bachelor-of-data-science-and-decisions",
    "universityDetailLink": "https://www.unsw.edu.au/"
  },
  {
    "subject": "Dentistry",
    "level": "undergraduate",
    "destination": "UK",
    "university": "King's College London",
    "ieltsScore": 7.0,
    "location": "London",
    "campusCity": "London",
    "tuitionFees": "£41,000 per year",
    "applicationFees": "£75",
    "duration": "5 years",
    "intake": "September",
    "worldRank": 33,
    "internationalStudent": "18%",
    "courseDetailLink": "https://www.kcl.ac.uk/study/undergraduate/courses/dentistry-bds",
    "universityDetailLink": "https://www.kcl.ac.uk/"
  },
  {
    "subject": "Earth Sciences",
    "level": "undergraduate",
    "destination": "Canada",
    "university": "McMaster University",
    "ieltsScore": 6.0,
    "location": "Hamilton",
    "campusCity": "Hamilton",
    "tuitionFees": "C$38,000 per year",
    "applicationFees": "C$110",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 144,
    "internationalStudent": "13%",
    "courseDetailLink": "https://earthsciences.mcmaster.ca/undergraduate/",
    "universityDetailLink": "https://www.mcmaster.ca/"
  },
  {
    "subject": "Econometrics",
    "level": "postgraduate",
    "destination": "USA",
    "university": "University of Chicago",
    "ieltsScore": 6.0,
    "location": "Chicago",
    "campusCity": "Chicago",
    "tuitionFees": "$60,552 per year",
    "applicationFees": "$75",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 10,
    "internationalStudent": "21%",
    "courseDetailLink": "https://econometrics.uchicago.edu/undergraduate/",
    "universityDetailLink": "https://www.uchicago.edu/"
  },
  {
    "subject": "Education",
    "level": "postgraduate",
    "destination": "Australia",
    "university": "University of Adelaide",
    "ieltsScore": 7.5,
    "location": "Adelaide",
    "campusCity": "Adelaide",
    "tuitionFees": "A$35,500 per year",
    "applicationFees": "A$110",
    "duration": "4 years",
    "intake": "February",
    "worldRank": 106,
    "internationalStudent": "27%",
    "courseDetailLink": "https://www.adelaide.edu.au/degree-finder/bmed_bmedsc.html",
    "universityDetailLink": "https://www.adelaide.edu.au/"
  },
  {
    "subject": "Electrical Engineering",
    "level": "undergraduate",
    "destination": "UK",
    "university": "University of Manchester",
    "ieltsScore": 6.5,
    "location": "Manchester",
    "campusCity": "Manchester",
    "tuitionFees": "£24,000 per year",
    "applicationFees": "£75",
    "duration": "3 years",
    "intake": "September",
    "worldRank": 27,
    "internationalStudent": "18%",
    "courseDetailLink": "https://www.manchester.ac.uk/study/undergraduate/courses/2022/07657/beng-electrical-and-electronic-engineering/",
    "universityDetailLink": "https://www.manchester.ac.uk/"
  },
  {
    "subject": "Environmental Engineering",
    "level": "phD",
    "destination": "Ireland",
    "university": "University College Cork",
    "ieltsScore": 6.5,
    "location": "Cork",
    "campusCity": "Cork",
    "tuitionFees": "€22,000 per year",
    "applicationFees": "€50",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 286,
    "internationalStudent": "15%",
    "courseDetailLink": "https://www.ucc.ie/en/ck602/",
    "universityDetailLink": "https://www.ucc.ie/"
  },
  {
    "subject": "Film Studies",
    "level": "phD",
    "destination": "Canada",
    "university": "University of Western Ontario",
    "ieltsScore": 6.5,
    "location": "London",
    "campusCity": "London",
    "tuitionFees": "C$36,208 per year",
    "applicationFees": "C$166",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 203,
    "internationalStudent": "18%",
    "courseDetailLink": "https://filmstudies.uwo.ca/",
    "universityDetailLink": "https://www.uwo.ca/"
  },
  {
    "subject": "Fine Arts",
    "level": "phD",
    "destination": "USA",
    "university": "Rhode Island School of Design",
    "ieltsScore": 6.0,
    "location": "Providence",
    "campusCity": "Providence",
    "tuitionFees": "$52,860 per year",
    "applicationFees": "$60",
    "duration": "4 years",
    "intake": "September",
    "worldRank": 26,
    "internationalStudent": "33%",
    "courseDetailLink": "https://www.risd.edu/academics/undergraduate",
    "universityDetailLink": "https://www.risd.edu/"
  },
  {
    subject: "Food Science",
    level: "postgraduate",
    destination: "Australia",
    university: "University of New England",
    ieltsScore: 6.5,
    location: "Armidale",
    campusCity: "Armidale",
    tuitionFees: "A$34,000 per year",
    applicationFees: "A$75",
    duration: "3 years",
    intake: "February",
    worldRank: 701,
    internationalStudent: "17%",
    courseDetailLink: "https://www.une.edu.au/study/study-options/find-a-course/food-science-and-nutrition",
    universityDetailLink: "https://www.une.edu.au/"
  }
]
